#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

verify_ssh_key_file() {
  declare desc="Test that public key is valid"
  [[ -s ${DOKKU_ROOT}/.ssh/authorized_keys ]] || dokku_log_fail "No public keys found."
  local key line=0
  set -xv
  local tmp_key_file="$(mktemp)"
  while read key ; do
    line=$((line + 1))
    echo "$key" > "$tmp_key_file"
    ssh-keygen -l -f "$tmp_key_file" &> /dev/null || { rm "$tmp_key_file"; dokku_log_fail "${DOKKU_ROOT}/.ssh/authorized_keys line $line failed ssh-keygen check."; }
  done <"${DOKKU_ROOT}/.ssh/authorized_keys"
  rm "$tmp_key_file"
}

verify_ssh_key_exists() {
  declare desc="Test that public key exists"
  [[ -e ${DOKKU_ROOT}/.ssh/authorized_keys ]] || dokku_log_fail "No public keys found."
}

create_ssh_key_file() {
  declare desc="Ensure the public key file exists"
  touch "${DOKKU_ROOT}/.ssh/authorized_keys"
}
